version: "2"
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
  csslint:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "vendor/"
  - "app/assets/javascripts/vendor"
  - "app/assets/stylesheets/vendor"
